# -*- coding: utf-8 -*-
"""Tharini-AI-Learning-Buddy.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1dJ8CL6fpdmy0hCtEKKSOctx_ZjYAh-dj
"""



import subprocess
import time
from pyngrok import ngrok

# 1. Authenticate
ngrok.set_auth_token("3FrBNp1NYZ0dmO8mhQDEWeWfjya_5tJWMoSgcpjRM93MEVvqf")

# 2. Programmatically close any active ghost tunnels held by ngrok's servers
print("Force-closing existing cloud tunnels...")
try:
    active_tunnels = ngrok.get_tunnels()
    for tunnel in active_tunnels:
        ngrok.disconnect(tunnel.public_url)
        print(f"Closed: {tunnel.public_url}")
except Exception as e:
    print("No active tunnels found in local memory pool.")

# 3. Kill local background tasks


ngrok.kill()
time.sleep(2)

# 4. Restart Streamlit
print("Starting Streamlit...")
subprocess.Popen(["streamlit", "run", "app.py", "--server.port", "8501"])
time.sleep(5)

# 5. Connect cleanly to your port
print("Opening fresh tunnel link...")
try:
    public_url = ngrok.connect(8501)
    print("\n🎉 SUCCESS! Click the link below to open your app:")
    print(public_url)
except Exception as e:
    print(f"\nConnection errored: {e}")
    print("👉 If it still says already online, wait 30 seconds and run this cell one final time for the server cache to clear.")

import subprocess
import time


# 1. Clear out any previous remnants


# 2. Boot up your Streamlit application
print("Starting Streamlit server...")
subprocess.Popen(["streamlit", "run", "app.py", "--server.port", "8501"])

# 3. Give it 4 seconds to turn on
time.sleep(4)

# 4. Use Google's internal API to route port 8501 to a safe browser link


print("\n🎉 SUCCESS! Click your built-in Google proxy link below:")

# Commented out IPython magic to ensure Python compatibility.
# %%writefile app.py
# 
# import streamlit as st
# import google.generativeai as genai
# 
# # Configure Gemini API
# 
# 
# model = genai.GenerativeModel("gemini-2.5-flash")
# 
# st.set_page_config(page_title="AI Learning Buddy Tharini", page_icon="🎓")
# st.title("🎓 AI Learning Buddy Tharini")
# 
# topic = st.text_input("Enter a Topic")
# option = st.selectbox(
#     "Choose Activity",
#     ["Explain Concept", "Real-Life Example", "Generate Quiz", "Ask Anything"]
# )
# 
# if st.button("Generate"):
#     if topic == "":
#         st.warning("Please enter a topic.")
#     else:
#         if option == "Explain Concept":
#             prompt = f"Explain {topic} in simple language for a beginner."
#         elif option == "Real-Life Example":
#             prompt = f"Give one simple real-life example of {topic}."
#         elif option == "Generate Quiz":
#             prompt = f"Create 5 MCQs on {topic} with answers."
#         else:
#             prompt = topic
# 
#         response = model.generate_content(prompt)
#         st.write(response.text)

import subprocess
import time
from google.colab.output import eval_js

# 1. Force kill any existing background instances to start clean


# 2. Launch Streamlit while disabling CORS, XSRF, and WebSocket Compression checks
print("Launching Streamlit with proxy security bypassed...")
subprocess.Popen([
    "streamlit", "run", "app.py",
    "--server.port", "8501",
    "--server.enableCORS", "false",
    "--server.enableXsrfProtection", "false",
    "--server.enableWebsocketCompression", "false"
])

# 3. Give the server a few seconds to wake up
time.sleep(4)

# 4. Generate the Google Colab internal link again


print("\n🎉 SUCCESS! Click this link to open your project:")
print(public_url)
